name: docs site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

concurrency:
  group: "deploy-docs-site"
  cancel-in-progress: true

jobs:
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Configure pages
        uses: actions/configure-pages@v2
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build site
        run: yarn build:docs
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "site"
      - name: Deploy pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v1
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: github_deployment
        with:
          token: "${{ github.token }}"
          environment-url: http://codedocs.ambic.app
          environment: production
